#!/usr/bin/env python3
"""Rewrite a prototype's hardcoded CSS values as design-system tokens.

Replaces raw hex colours, font sizes and radii with var(--ff-*) references
generated from the Flutter theme, so the developer reads a token name instead
of guessing which token a hex was meant to be.

Three tiers, by distance from the nearest token:
  <= SNAP_TIER1   substituted silently -- same colour, just named
  <= SNAP_TIER2   substituted and listed in HANDOFF.md for review
  >  SNAP_TIER2   left alone and flagged -- a real new design decision

Prototype chrome (the dark page around the device frame) is deliberately left
untokenized: it is not part of the app.

Usage:
    python3 tools/apply_tokens.py edeka-dankenbring.html
    python3 tools/apply_tokens.py edeka-dankenbring.html --dry-run
"""

import argparse
import collections
import json
import math
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SNAP_TIER1 = 12.0
SNAP_TIER2 = 40.0
SNAP_PX = 1.0

BEGIN = "/* FF-TOKENS:BEGIN -- generated by tools/gen_ff_tokens.py, do not edit */"
END = "/* FF-TOKENS:END */"

# Selectors belonging to the prototype scaffolding rather than the app UI.
CHROME = re.compile(r"^\s*(html\s*,\s*body|body|\.stage|\.note|\.legend)\b")

# Prototype-only additions that have no Flutter token yet.
EXTENSIONS = """
/* --- prototype extensions: NO Flutter token exists for these yet --- */
/* A fully-rounded pill. The app's largest radius is c50 (50px), which is not
   the same thing at these heights. Needs an AppBorderRadius.pill decision. */
:root { --ff-radius-pill: 999px; }
"""


def rgb(css):
    css = css.strip().lower()
    m = re.fullmatch(r"#([0-9a-f]{3})", css)
    if m:
        return tuple(int(c * 2, 16) for c in m.group(1))
    m = re.fullmatch(r"#([0-9a-f]{6})", css)
    if m:
        h = m.group(1)
        return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))
    return None


def dist(a, b):
    rm = (a[0] + b[0]) / 2
    dr, dg, db = a[0] - b[0], a[1] - b[1], a[2] - b[2]
    return math.sqrt((2 + rm / 256) * dr ** 2 + 4 * dg ** 2 + (2 + (255 - rm) / 256) * db ** 2)


def rank(var):
    """Prefer the name a developer would reach for first."""
    if re.match(r"--ff-(grey|primary|orange)-\d+$", var):
        return 0
    if var.startswith("--ff-color-k-"):
        return 4
    if var.startswith("--ff-color-chart-"):
        return 3
    if var.startswith("--ff-color-tag-"):
        return 2
    if var.startswith("--ff-text-primary-") or var.startswith("--ff-radius-"):
        return 0
    if var.startswith("--ff-text-secondary-"):
        return 1
    if var.startswith("--ff-text-"):
        return 3
    return 1


def best_color(value, table):
    r = rgb(value)
    if r is None:
        return None, 1e9
    scored = []
    for var, css in table.items():
        t = rgb(css)
        if t is not None:
            scored.append((dist(r, t), rank(var), var))
    if not scored:
        return None, 1e9
    floor = min(s[0] for s in scored)
    # among near-ties, let the nicer name win
    scored = [s for s in scored if s[0] <= floor + 2.0]
    scored.sort(key=lambda s: (s[1], s[0]))
    return scored[0][2], scored[0][0]


def best_num(px, table):
    scored = sorted(
        ((abs(px - float(v)), rank(k), k) for k, v in table.items()),
        key=lambda s: (round(s[0], 3), s[1]),
    )
    return (scored[0][2], scored[0][0]) if scored else (None, 1e9)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("html", type=pathlib.Path)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--font-family", default="primary",
                    choices=["primary", "secondary", ""],
                    help="only match text styles from this AppFonts family")
    ap.add_argument("--include-unused", action="store_true",
                    help="allow tokens the app declares but never reads")
    ap.add_argument("--include-charts", action="store_true",
                    help="allow the data-viz chart palette to win UI colour matches")
    ap.add_argument("--max-delta", type=float, default=SNAP_TIER2,
                    help="only substitute colours within this distance of a token; "
                         "pass 0 for a pure rename with zero visual change")
    ap.add_argument("--report", type=pathlib.Path, default=REPO / "HANDOFF.md")
    args = ap.parse_args()
    globals()["SNAP_TIER2"] = args.max_delta

    tj = REPO / "assets" / "ff-tokens.json"
    if not tj.exists():
        sys.exit("run tools/gen_ff_tokens.py first")
    T = json.loads(tj.read_text(encoding="utf-8"))
    colors = dict(T["colors"]); colors.update(T["swatches"])
    usage = T.get("usage", {})
    text = dict(T["text"])

    if not args.include_unused:
        # A token the app never reads is aspirational, not a precedent. Pointing
        # the prototype at one tells the developer "match this", when nothing in
        # the app actually looks like that.
        colors = {k: v for k, v in colors.items() if usage.get(k, 1) > 0}
        text = {k: v for k, v in text.items() if usage.get(k, 1) > 0}

    # Component-scoped text styles are not a general scale: textfieldLabel
    # carries height:0.25, dropDownItem is the dropdown's own style. They must
    # not win a generic font-size match just by having the right px.
    text = {k: v for k, v in text.items()
            if not k.startswith("--ff-text-textfield")
            and k != "--ff-text-drop-down-item"}

    # This prototype renders entirely in Inter (AppFonts.primary). Matching a
    # size onto a secondary-font style would name a Euclid Circular style for
    # text that is not set in Euclid Circular.
    fam = T.get("text_family", {})
    if args.font_family:
        text = {k: v for k, v in text.items()
                if fam.get(k, "primary") == args.font_family}

    if not args.include_charts:
        # Chart colours are a data-viz palette. They are often numerically close
        # to a neutral grey, which makes them win a nearest-match they have no
        # business winning -- a divider is not chart10.
        colors = {k: v for k, v in colors.items() if not k.startswith("--ff-color-chart-")}
    css = (REPO / "assets" / "ff-tokens.css").read_text(encoding="utf-8")

    src = args.html.read_text(encoding="utf-8")
    review, newvals, chrome_skips = [], collections.Counter(), collections.Counter()
    applied = collections.Counter()

    HEX = re.compile(r"#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b")
    # A colour that is an entire JS string ('#RRGGBB') feeds canvas, where
    # var() does not resolve. Snap the literal instead and name it in a comment.
    LITERAL = re.compile(r"(['\"])(#[0-9a-fA-F]{6})\1")

    def sub_hex(text, allow_var=True):
        def repl(m):
            v = m.group(0)
            var, d = best_color(v.lower(), colors)
            if var is None or d > SNAP_TIER2:
                newvals[v.lower()] += 1
                return v
            if d >= 0.5:
                review.append(("colour", v.lower(), var, colors[var], d))
            applied["colour"] += 1
            return "var(%s)" % var if allow_var else colors[var]
        return HEX.sub(repl, text)

    WEIGHT = re.compile(r"(font-weight\s*:\s*)(\d{3})\b")

    def sub_weight(text):
        by_val = {}
        for var, val in T["weights"].items():
            by_val.setdefault(int(val), var)
        def repl(m):
            v = int(m.group(2))
            var = by_val.get(v)
            if var is None:
                newvals["font-weight %d" % v] += 1
                return m.group(0)
            applied["font weight"] += 1
            return m.group(1) + "var(%s)" % var
        return WEIGHT.sub(repl, text)

    def sub_px(text, prop, table, kind):
        pat = re.compile(r"(%s\s*:\s*)([\d.]+)px" % prop)
        def repl(m):
            px = float(m.group(2))
            var, d = best_num(px, table)
            if kind == "radius" and px >= 50:
                applied[kind] += 1
                return m.group(1) + "var(--ff-radius-pill)"
            if var is None or d > SNAP_PX:
                newvals["%s %gpx" % (kind, px)] += 1
                return m.group(0)
            if d > 0:
                review.append((kind, "%gpx" % px, var, table[var], d))
            applied[kind] += 1
            return m.group(1) + "var(%s)" % var
        return pat.sub(repl, text)

    # ---- split the document -------------------------------------------------
    i, j = src.index("<style>") + len("<style>"), src.index("</style>")
    head, style, tail = src[:i], src[i:j], src[j:]

    # ---- stylesheet: skip prototype chrome ---------------------------------
    out = []
    for line in style.split("\n"):
        sel = line.split("{", 1)[0] if "{" in line else ""
        if sel and CHROME.match(sel):
            for h in HEX.findall(line):
                chrome_skips[h.lower()] += 1
            out.append(line)
            continue
        line = sub_hex(line)
        line = sub_px(line, "font-size", text, "font size")
        line = sub_px(line, "border-radius", T["radii"], "radius")
        line = sub_weight(line)
        out.append(line)
    style = "\n".join(out)

    # ---- body + script ------------------------------------------------------
    lit_hits, vault = [], []
    def lit_repl(m):
        q, v = m.group(1), m.group(2)
        var, d = best_color(v.lower(), colors)
        if var is None or d > SNAP_TIER2:
            newvals[v.lower()] += 1
            return m.group(0)
        if d >= 0.5:
            review.append(("colour (canvas)", v.lower(), var, colors[var], d))
        lit_hits.append((v.lower(), var))
        applied["colour"] += 1
        # Park it behind a placeholder so the general hex pass below cannot
        # turn it back into a var() -- that would break <canvas>.
        vault.append("%s%s%s" % (q, colors[var], q))
        return "\x00FFLIT%d\x00" % (len(vault) - 1)

    tail = LITERAL.sub(lit_repl, tail)
    tail = sub_hex(tail)
    tail = sub_px(tail, "font-size", text, "font size")
    tail = sub_px(tail, "border-radius", T["radii"], "radius")
    tail = sub_weight(tail)
    tail = re.sub(r"\x00FFLIT(\d+)\x00", lambda m: vault[int(m.group(1))], tail)

    # ---- inject the token block --------------------------------------------
    block = "\n%s\n%s\n%s\n%s\n" % (BEGIN, css.strip(), EXTENSIONS.strip(), END)
    style = re.sub(r"\n?%s.*?%s\n?" % (re.escape(BEGIN), re.escape(END)), "", style, flags=re.S)
    style = block + style

    result = head + style + tail

    if args.dry_run:
        print("dry run -- nothing written")
    else:
        args.html.write_text(result, encoding="utf-8")

    if args.dry_run:
        # Writing the report on a dry run would overwrite an accurate report
        # with counts from a file that was already migrated.
        print("dry run -- report not written")
        return

    # ---- report -------------------------------------------------------------
    R = []
    R.append("# Handoff notes -- %s\n" % args.html.name)
    R.append("Generated by `tools/apply_tokens.py`. Regenerate with:\n")
    R.append("```bash\npython3 tools/gen_ff_tokens.py && python3 tools/apply_tokens.py %s\n```\n"
             % args.html.name)
    R.append("Every colour, font size and radius below now reads as a `var(--ff-*)` "
             "token generated from `Mobile/lib/core/theme/*.dart`. A value that is "
             "**not** a token is a deliberate new design decision, listed at the bottom.\n")
    R.append("## Substituted\n")
    for k in sorted(applied):
        R.append("- %s: %d values now tokenized" % (k, applied[k]))
    R.append("")

    if review:
        vis = [r for r in review if r[4] > SNAP_TIER1]
        R.append("## Values that MOVED -- please sanity-check\n")
        R.append("These were close to a token but not identical. Substituting the token "
                 "changed the rendered value slightly. %d of them moved far enough to be "
                 "worth a look (delta > %g); the rest are imperceptible.\n"
                 % (len(set((r[1], r[2]) for r in vis)), SNAP_TIER1))
        R.append("Everything not listed here was an *exact* token match -- renamed, not "
                 "changed.\n")
        R.append("| kind | was | now | token value | delta |")
        R.append("|---|---|---|---|---|")
        seen = set()
        for kind, was, var, val, d in sorted(review, key=lambda r: -r[4]):
            if (kind, was, var) in seen:
                continue
            seen.add((kind, was, var))
            R.append("| %s | `%s` | `var(%s)` | `%s` | %.1f |" % (kind, was, var, val, d))
        R.append("")

    if newvals:
        R.append("## No token exists -- design decisions still open\n")
        R.append("These have no counterpart in the Flutter theme. Each one needs either "
                 "a mapping to an existing token, or a new token added to the Dart source "
                 "before it ships.\n")
        R.append("| value | uses |")
        R.append("|---|---|")
        for v, n in newvals.most_common():
            R.append("| `%s` | %d |" % (v, n))
        R.append("")

    if chrome_skips:
        R.append("## Deliberately NOT tokenized -- prototype chrome\n")
        R.append("The dark page around the device frame (`html/body`, `.stage`, `.note`, "
                 "`.legend`) is scaffolding for viewing the prototype in a browser. "
                 "It is not part of the app and should not be built.\n")
        R.append("Colours skipped: %s\n" % ", ".join("`%s`" % c for c in sorted(chrome_skips)))

    if lit_hits:
        R.append("## Canvas colours\n")
        R.append("`var()` does not resolve inside `<canvas>`, so these stayed literal. "
                 "The value is now exactly the token's value:\n")
        for v, var in sorted(set(lit_hits)):
            R.append("- `%s` = `%s`" % (v, var))
        R.append("")

    # Hand-written notes live outside this script so regenerating the report
    # cannot silently destroy them.
    appendix = REPO / "tools" / "handoff_appendix.md"
    if appendix.exists():
        R.append(appendix.read_text(encoding="utf-8"))

    args.report.write_text("\n".join(R), encoding="utf-8")
    print("tokenized: %s" % dict(applied))
    print("to review: %d   still untokenized: %d uses   chrome skipped: %d"
          % (len(set((r[1], r[2]) for r in review)), sum(newvals.values()),
             sum(chrome_skips.values())))
    print("report -> %s" % args.report)


if __name__ == "__main__":
    main()
